//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apraiseditem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AppraiseNo { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> AppraisedValue { get; set; }
        public string CustomerName { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
