//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class apraiseditem
    {
        public int AppraiseId { get; set; }
        public Nullable<System.DateTime> AppraiseDate { get; set; }
        public string AppraiseNo { get; set; }
        public string ItemCategoryId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> AppraisedValue { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<bool> IsPawned { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerId { get; set; }
        public Nullable<bool> isPawned { get; set; }
    }
}
