//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemcategory
    {
        public int ItemCategoryId { get; set; }
        public string ItemCategoryName { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
