//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_category_info
    {
        public long autonum { get; set; }
        public string bar_code { get; set; }
        public string category_desc1 { get; set; }
        public string category_desc2 { get; set; }
        public string category_desc3 { get; set; }
        public string category_desc4 { get; set; }
    }
}
