//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ipos_karat
    {
        public long autonum { get; set; }
        public Nullable<int> karat_code { get; set; }
        public string karat_desc { get; set; }
    }
}
