//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_add_info
    {
        public long autonum { get; set; }
        public string company_code { get; set; }
        public Nullable<int> ul_code { get; set; }
        public string bar_code { get; set; }
        public Nullable<float> min_qty { get; set; }
        public Nullable<float> max_qty { get; set; }
        public Nullable<float> reorder_qty { get; set; }
        public Nullable<float> inv_buildup { get; set; }
        public Nullable<float> day_to_ST { get; set; }
        public Nullable<double> daily_ave { get; set; }
        public Nullable<System.DateTime> last_sales_date { get; set; }
        public string regular_or_phaseout { get; set; }
        public string active_or_inactive { get; set; }
        public string trade_or_nontrade { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<float> serial_no { get; set; }
        public Nullable<double> supervisordiscount_from { get; set; }
        public Nullable<double> supervisordiscount_to { get; set; }
        public Nullable<double> cashierdiscount_from { get; set; }
        public Nullable<double> cashierdiscount_to { get; set; }
    }
}
