//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public long autonum { get; set; }
        public string company_code { get; set; }
        public Nullable<int> ul_code { get; set; }
        public string item_type { get; set; }
        public Nullable<int> category_id { get; set; }
        public string category { get; set; }
        public Nullable<int> principal_id { get; set; }
        public string principal { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string style { get; set; }
        public string p_size { get; set; }
        public string color { get; set; }
        public Nullable<float> qty_onhand { get; set; }
        public Nullable<float> qty_avl { get; set; }
        public string uom { get; set; }
        public string item_code { get; set; }
        public string bar_code { get; set; }
        public string alternate_code { get; set; }
        public string long_desc { get; set; }
        public string short_desc { get; set; }
        public Nullable<double> reg_price { get; set; }
        public Nullable<double> key_price { get; set; }
        public Nullable<double> ws_price { get; set; }
        public Nullable<double> ec_price { get; set; }
        public Nullable<double> last_purch { get; set; }
        public Nullable<double> standard_price { get; set; }
        public Nullable<double> rm_cost { get; set; }
        public Nullable<double> dl_cost { get; set; }
        public Nullable<double> oh_cost { get; set; }
        public Nullable<double> ave_cost { get; set; }
        public Nullable<double> fifo_cost { get; set; }
        public string tax_code { get; set; }
        public byte[] prod_img { get; set; }
        public string active { get; set; }
        public string with_serial { get; set; }
        public string batch_code { get; set; }
    }
}
