//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPOS.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ipos_pawneditem
    {
        public int PawnedItemId { get; set; }
        public string PawnedItemNo { get; set; }
        public System.DateTime PawnedDate { get; set; }
        public string PawnshopTransactionNo { get; set; }
        public int AppraiseId { get; set; }
        public int CustomerId { get; set; }
        public string PawnedItemContractNo { get; set; }
        public decimal LoanableAmount { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal InitialPayment { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal Others { get; set; }
        public bool IsInterestDeducted { get; set; }
        public decimal NetCashOut { get; set; }
        public string TermsId { get; set; }
        public string ScheduleOfPayment { get; set; }
        public int NoOfPayments { get; set; }
        public System.DateTime DueDateStart { get; set; }
        public System.DateTime DueDateEnd { get; set; }
        public string Status { get; set; }
        public bool IsReleased { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
